### ISSUE TITLE
Import SDS Cluster API

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-api#10]
As a user of tendrl, I should be able to import an existing sds cluster.

Assumptions:
- Tendrl node agent is installed, configured and running on all the sds cluster nodes.
- Tendrl central store (etcd) should be accessible to all above node agents

Bootstrapping:
- tendrl-api to find node agent definition yaml at /nodes/tendrl_node_agent_definition.yaml
- tendrl-api to find discovered sds_name and sds_version at /nodes/$node.id/metadata

@anivargi let me know if any more inputs required

**Comment by anivargi** [comment]
Was fixed as part of https://github.com/Tendrl/tendrl-api/releases/tag/v1.0
