### ISSUE TITLE
Tendrl Definitions file structure

### ISSUE THREAD

**Issue by fbalak** [Tendrl/tendrl-api#19]
In README.adoc is written: 

> Tendrl Definitions:
> 
> The API needs the proper Tendrl definitions yaml file to generate the attributes and actions. You can either download it or use the one from the fixtures to explore the API.
> 

> 
> ```
> [tendrl-api] $ cp spec/fixtures/sds/tendrl_definitions_gluster-3.8.3.yaml \
>                config/sds/tendrl_definitions_gluster-3.8.3.yaml
> ```
> 

but there is no spec/fixtures/sds directory in git repo. There are some definition files in spec/fixtures/definitions but it is not clear how to use them.

**Comment by brainfunked** [comment]
@fbalak Those are required only if you wish to run the unit tests. In any case, it looks like the path in the documentation is still wrong, which I'll fix.

**Comment by anivargi** [comment]
@fbalak @brainfunked this is outdated due to the definitions changes. So closing.
