### ISSUE TITLE
tendrl-apid doesn't run

### ISSUE THREAD

**Issue by fbalak** [Tendrl/tendrl-api#27]
There are some errors when command 'service tendrl-apid start' is executed:
```
[/usr/lib/systemd/system/tendrl-apid.service:6] Executable path is not absolute, ignoring: vendor/bin/puma -e production -d
tendrl-apid.service lacks both ExecStart= and ExecStop= setting. Refusing.
```
Service won't run. In /usr/lib/systemd/system/tendrl-apid.service is probably mistyped:
`ExecStart=vendor/bin/puma -e production -d`

**Comment by brainfunked** [comment]
How did `vendor/bin/puma` end up in the service file? https://github.com/Tendrl/tendrl-api/blob/master/tendrl-apid.service shows it to be `/usr/bin/puma`.

**Comment by anivargi** [comment]
@fbalak can you verify the version of the rpm that you are using is the latest one? Also can you tell us more about your environment where you are trying to run this?

**Comment by fbalak** [comment]
It is tendrl-api-0.0.1-8.el7.centos.noarch package and I run it on Centos 7.2.

**Comment by mkudlej** [comment]
I've tried ```/usr/bin/puma``` and it doesn't work too.

**Comment by fbalak** [comment]
After installing tendrl-api from https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/ service tendrl-apid runs.
