### ISSUE TITLE
We need a generic non-human account for automated tasks

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-api#3]

**Comment by sankarshanmukhopadhyay** [comment]
Citing https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/ it seems that bot accounts are essentially no different from an user account. Is this to be consumed by automation or, similar?

**Comment by r0h4n** [comment]
@sankarshanmukhopadhyay , Yes, we need a bot account in github for Travis, Coveralls and in future we would also be automating the merge process which will happen only after a successful human review

**Comment by sankarshanmukhopadhyay** [comment]
@r0h4n - can I have a name? I think I comprehend the notion of what needs to be done.

**Comment by r0h4n** [comment]
"tendrl_github" or "tendrl_bot" works for me

**Comment by nthomas-redhat** [comment]
I vote for 'tendrl_bot'

**Comment by anivargi** [comment]
Whats the status here?
