### ISSUE TITLE
No systemd unit file for puma webserver in puma.spec file

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-api#34]
There is no systemd unit file for puma daemon in puma.spec file.

**Comment by mbukatov** [comment]
Are you seriously considering maintenance of other rpm packages in this repository?

**Comment by TimothyAsir** [comment]
Actually puma does not provide any specific daemon for managing that service. We are just using whatever puma provides. Where as we are having a seperate service called tendrl-apid which helps to manage puma by starting, stopping, restarting and so on based on our tendrl-api uses.

**Comment by mbukatov** [comment]
Thanks for the update. It seems to me that the puma is more like a web server library, so that the service unit file is provided for  `tendrl-api` rather then puma itself, and that puma can't be started alone without the `tendrl-api`, am I right?

**Comment by TimothyAsir** [comment]
yes you are right, puma can't be started alone without tendrl-api.

**Comment by mbukatov** [comment]
Related upstream documentation: https://github.com/puma/puma/blob/master/docs/systemd.md

**Comment by mbukatov** [comment]
Based on the explanation from @TimothyAsir and upstream documentation (linked above), I'm closing this issue. Puma systemd service file is not expected to be present in the package. There is a service file for the tendrl-api instead, which is the correct approach here.
