### ISSUE TITLE
tendrl-api: install instructions documentation

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-api#6]
There should be document which describes:

what software should be installed and how should be configured before installing tendrl-api
tendrl-api installation process
tendrl-api post installation steps like configuration, service starting and so on

**Comment by anivargi** [comment]
@r0h4n this is going to be part of the Tendrl/tendrl repo README

**Comment by r0h4n** [comment]
@anupnivargi ok, is it WIP? PR?

**Comment by anivargi** [comment]
@r0h4n it is part of thttps://github.com/Tendrl/tendrl/pull/7 README.md

**Comment by sankarshanmukhopadhyay** [comment]
Alright - it is not clear as to what remains to be done for this issue. Anyone?
