### ISSUE TITLE
delete the Tendrl/tendrl repo

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-api#9]
Hi @r0h4n @brainfunked @sankarshanmukhopadhyay  - I would like to delete this empty repo unless we have plans for it. It tends to confuse newcomers. There are open issues on it - perhaps they should be closed first?

**Comment by r0h4n** [comment]
@anivargi owns a PR on this repo, That and the open issues need to be closed. No problems after that

**Comment by mkudlej** [comment]
@japplewhite It seems that this repo is for API, isn't it?

**Comment by mbukatov** [comment]
Assuming this repository is here for the tendrl api component, could you at least rename this repo to something more meaningful?

**Comment by r0h4n** [comment]
@brainfunked @anivargi are you guys ok with this removal?

**Comment by anivargi** [comment]
@japplewhite we can rename it to tendrl-api?

**Comment by anivargi** [comment]
The repo has been named to tendrl-api now, so closing.
